# Generated by Django 3.0.2 on 2020-06-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='file_name',
        ),
    ]
