# Generated by Django 3.0.2 on 2020-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_imageupload_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image_file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
